### ISSUE TITLE
home.html Side Navigation Bar Fails to Update

### ISSUE THREAD

**Issue by DerDoktorFaust** [TonLeon/mindoc#4]
Process to reproduce the issue:

1. Edit 007_credits_acknowledgments.md and change title to "test". Commit changes.
2. Wait for site to update.
3. The side navigation bar will have updated on every page BUT NOT the home page
4. Go to _layouts/home.html
5. Edit home.html by changing something in the text (for example change intro to introduction). Commit change
6. Go to the home page and check if navigation bar has updated

After several tests, the only way to update the navigation bar on the home page is to commit a change to it. It will not change unless I commit a change. However, all other pages (the .md pages), those sidebars will change once you change title in one of the other .md files.

**Comment by carolinekness** [comment]
I don't believe I was able to recreate the bug. When I edited the code for 008_about_sourcelab.md to change the navigation tab and section title to About MinDoc Template, the changes were reflected from the home page without having to edit the _layouts/home.html section. When I edited the files, I was not able to remain the folders themselves in the repository (such as renaming 008_about_sourcelab.md to 008.about_mindoc.md).

**Comment by TonLeon** [comment]
I also don't have this bug. Rn I did the following:
1) I opened 008_about_sourcelab.md
2) I changed the YAML front-matter part and changed the title of the page from "About Sourcelab" to "About Mindoc"
3) I changed the body of this document and wrote "About Mindoc" in the body instead of "About Sourcelab"
4) I renamed  008_about_sourcelab.md to 008_about_mindoc.md (at the top of the document where the path to it is written)
5) I committed the changes, which included the change of the name and the change of the document itself
6) I checked the website itself, and it looks like everything works as it should

**Comment by DerDoktorFaust** [comment]
I created a new repository with the most current version of Min-Doc--And the issue appears resolved!! 

On my older version the issue is still there and I didn't change any fundamental features from that version of the repository.

So it seems like the bug doesn't exist anymore! 

Thanks for testing!
